-- MySQL Script generated by MySQL Workbench
-- Tue May  2 10:35:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SaudeSempre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SaudeSempre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SaudeSempre` DEFAULT CHARACTER SET utf8 ;
USE `SaudeSempre` ;

-- -----------------------------------------------------
-- Table `SaudeSempre`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaudeSempre`.`Endereco` (
  `idEndereco` INT NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SaudeSempre`.`Consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaudeSempre`.`Consultorio` (
  `idConsultorio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idConsultorio`, `Endereco_idEndereco`),
  INDEX `fk_Consultorio_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Consultorio_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `SaudeSempre`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SaudeSempre`.`Atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaudeSempre`.`Atendente` (
  `idAtendente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `Consultorio_idConsultorio` INT NOT NULL,
  PRIMARY KEY (`idAtendente`, `Consultorio_idConsultorio`),
  INDEX `fk_Atendente_Consultorio1_idx` (`Consultorio_idConsultorio` ASC) VISIBLE,
  CONSTRAINT `fk_Atendente_Consultorio1`
    FOREIGN KEY (`Consultorio_idConsultorio`)
    REFERENCES `SaudeSempre`.`Consultorio` (`idConsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SaudeSempre`.`Atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaudeSempre`.`Atendimento` (
  `idAtendimento` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `diagnostico` VARCHAR(200) NOT NULL,
  `receita` VARCHAR(100) NULL,
  PRIMARY KEY (`idAtendimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SaudeSempre`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaudeSempre`.`Medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `Consultorio_idConsultorio` INT NOT NULL,
  `Atendimento_idAtendimento` INT NOT NULL,
  PRIMARY KEY (`idMedico`, `Consultorio_idConsultorio`, `Atendimento_idAtendimento`),
  INDEX `fk_Medico_Consultorio1_idx` (`Consultorio_idConsultorio` ASC) VISIBLE,
  INDEX `fk_Medico_Atendimento1_idx` (`Atendimento_idAtendimento` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_Consultorio1`
    FOREIGN KEY (`Consultorio_idConsultorio`)
    REFERENCES `SaudeSempre`.`Consultorio` (`idConsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_Atendimento1`
    FOREIGN KEY (`Atendimento_idAtendimento`)
    REFERENCES `SaudeSempre`.`Atendimento` (`idAtendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SaudeSempre`.`PlanoSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaudeSempre`.`PlanoSaude` (
  `idPlanoSaude` INT NOT NULL AUTO_INCREMENT,
  `nomePlano` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPlanoSaude`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SaudeSempre`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaudeSempre`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `PlanoSaude_idPlanoSaude` INT NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `Atendimento_idAtendimento` INT NOT NULL,
  PRIMARY KEY (`idPaciente`, `PlanoSaude_idPlanoSaude`, `Endereco_idEndereco`, `Atendimento_idAtendimento`),
  INDEX `fk_Paciente_PlanoSaude_idx` (`PlanoSaude_idPlanoSaude` ASC) VISIBLE,
  INDEX `fk_Paciente_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  INDEX `fk_Paciente_Atendimento1_idx` (`Atendimento_idAtendimento` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_PlanoSaude`
    FOREIGN KEY (`PlanoSaude_idPlanoSaude`)
    REFERENCES `SaudeSempre`.`PlanoSaude` (`idPlanoSaude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `SaudeSempre`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Atendimento1`
    FOREIGN KEY (`Atendimento_idAtendimento`)
    REFERENCES `SaudeSempre`.`Atendimento` (`idAtendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SaudeSempre`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaudeSempre`.`Consulta` (
  `idConsulta` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Paciente_PlanoSaude_idPlanoSaude` INT NOT NULL,
  `Paciente_Endereco_idEndereco` INT NOT NULL,
  `Atendente_idAtendente` INT NOT NULL,
  `Atendente_Consultorio_idConsultorio` INT NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  `Medico_Consultorio_idConsultorio` INT NOT NULL,
  `PlanoSaude_idPlanoSaude` INT NOT NULL,
  PRIMARY KEY (`idConsulta`, `Paciente_idPaciente`, `Paciente_PlanoSaude_idPlanoSaude`, `Paciente_Endereco_idEndereco`, `Atendente_idAtendente`, `Atendente_Consultorio_idConsultorio`, `Medico_idMedico`, `Medico_Consultorio_idConsultorio`),
  INDEX `fk_Consulta_Paciente1_idx` (`Paciente_idPaciente` ASC, `Paciente_PlanoSaude_idPlanoSaude` ASC, `Paciente_Endereco_idEndereco` ASC) VISIBLE,
  INDEX `fk_Consulta_Atendente1_idx` (`Atendente_idAtendente` ASC, `Atendente_Consultorio_idConsultorio` ASC) VISIBLE,
  INDEX `fk_Consulta_Medico1_idx` (`Medico_idMedico` ASC, `Medico_Consultorio_idConsultorio` ASC) VISIBLE,
  INDEX `fk_Consulta_PlanoSaude1_idx` (`PlanoSaude_idPlanoSaude` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente` , `Paciente_PlanoSaude_idPlanoSaude` , `Paciente_Endereco_idEndereco`)
    REFERENCES `SaudeSempre`.`Paciente` (`idPaciente` , `PlanoSaude_idPlanoSaude` , `Endereco_idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Atendente1`
    FOREIGN KEY (`Atendente_idAtendente` , `Atendente_Consultorio_idConsultorio`)
    REFERENCES `SaudeSempre`.`Atendente` (`idAtendente` , `Consultorio_idConsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Medico1`
    FOREIGN KEY (`Medico_idMedico` , `Medico_Consultorio_idConsultorio`)
    REFERENCES `SaudeSempre`.`Medico` (`idMedico` , `Consultorio_idConsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_PlanoSaude1`
    FOREIGN KEY (`PlanoSaude_idPlanoSaude`)
    REFERENCES `SaudeSempre`.`PlanoSaude` (`idPlanoSaude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SaudeSempre`.`Atendente_has_Atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaudeSempre`.`Atendente_has_Atendimento` (
  `Atendente_idAtendente` INT NOT NULL,
  `Atendente_Consultorio_idConsultorio` INT NOT NULL,
  `Atendimento_idAtendimento` INT NOT NULL,
  PRIMARY KEY (`Atendente_idAtendente`, `Atendente_Consultorio_idConsultorio`, `Atendimento_idAtendimento`),
  INDEX `fk_Atendente_has_Atendimento_Atendimento1_idx` (`Atendimento_idAtendimento` ASC) VISIBLE,
  INDEX `fk_Atendente_has_Atendimento_Atendente1_idx` (`Atendente_idAtendente` ASC, `Atendente_Consultorio_idConsultorio` ASC) VISIBLE,
  CONSTRAINT `fk_Atendente_has_Atendimento_Atendente1`
    FOREIGN KEY (`Atendente_idAtendente` , `Atendente_Consultorio_idConsultorio`)
    REFERENCES `SaudeSempre`.`Atendente` (`idAtendente` , `Consultorio_idConsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendente_has_Atendimento_Atendimento1`
    FOREIGN KEY (`Atendimento_idAtendimento`)
    REFERENCES `SaudeSempre`.`Atendimento` (`idAtendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SaudeSempre`.`Atendimento_has_Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaudeSempre`.`Atendimento_has_Medico` (
  `Atendimento_idAtendimento` INT NOT NULL,
  `Medico_idMedico` INT NOT NULL,
  `Medico_Consultorio_idConsultorio` INT NOT NULL,
  `Medico_Atendimento_idAtendimento` INT NOT NULL,
  PRIMARY KEY (`Atendimento_idAtendimento`, `Medico_idMedico`, `Medico_Consultorio_idConsultorio`, `Medico_Atendimento_idAtendimento`),
  INDEX `fk_Atendimento_has_Medico_Medico1_idx` (`Medico_idMedico` ASC, `Medico_Consultorio_idConsultorio` ASC, `Medico_Atendimento_idAtendimento` ASC) VISIBLE,
  INDEX `fk_Atendimento_has_Medico_Atendimento1_idx` (`Atendimento_idAtendimento` ASC) VISIBLE,
  CONSTRAINT `fk_Atendimento_has_Medico_Atendimento1`
    FOREIGN KEY (`Atendimento_idAtendimento`)
    REFERENCES `SaudeSempre`.`Atendimento` (`idAtendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimento_has_Medico_Medico1`
    FOREIGN KEY (`Medico_idMedico` , `Medico_Consultorio_idConsultorio` , `Medico_Atendimento_idAtendimento`)
    REFERENCES `SaudeSempre`.`Medico` (`idMedico` , `Consultorio_idConsultorio` , `Atendimento_idAtendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
